.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
This PR...
- Updated .github directory by adding an issue template folder with templates for feature and bug report
- Makes the creation of issues more clear.
Fixes #
=> docs:added issue templates

src/index.css
This PR...
- added CSS variables
-
Fixes #
=> feat:added some CSS color variables

src/index.css
This PR...
The main.css file by adding the CSS color variable names from the Figma document
=> Add CSS Color variables

.github/pull_request_template.md
This PR...
- Updated the pull request template
- Added a checkbox option for changes made to CSS styles
Fixes #
=> docs:updated pull request template

src/main.jsx, src/pages/auth/altStudent/altStudent.jsx, src/pages/auth/altStudent/altStudentLogin/altStudentLogin.jsx, src/pages/auth/altStudent/altStudentRegister/altStudentRegister.jsx, src/pages/auth/altStudent/index.js, src/pages/index.jsx
This PR...
- Added routes and nested routes
-
Fixes #
=> feat: updated routes

src/pages/auth/regularStudent/regularStudent.module.css
=> feat: test change

src/pages/auth/altStudent/altStudent.jsx, src/pages/auth/altStudent/altStudent.module.css, src/pages/auth/altStudent/altStudentRegister/altStudentRegister.jsx, src/pages/auth/altStudent/altStudentRegister/altStudentRegister.module.css
=> update ft. scaled down on the fontsizes and positioning

package.json
=> docs: gh-pages update

src/pages/auth/regularStudent/regularStudent.jsx, src/pages/auth/regularStudent/regularStudent.module.css, src/pages/auth/regularStudent/regularStudentRegister/regularStudentRegister.module.css, src/pages/auth/userLogin/forgotPassword/forgotPassword.module.css, src/pages/auth/userLogin/login/userLogin.module.css, vite.config.js
=> feat: responsiveness  for regularstudent & login

package-lock.json, src/pages/auth/altStudent/altStudent.module.css, src/pages/auth/altStudent/altStudentRegister/altStudentRegister.module.css, vite.config.js
=> feat: Worked on the responsiveness of the alt student authentication page

src/pages/dashboard/layout/layout.jsx
=> fix: relative path build issue

src/pages/dashboard/components/sidebar/sidebar.jsx
=> bug: replaced wrong path for "notifications" route

src/app/slices/apiSlices/authSlice.js, src/app/store.js, src/main.jsx, src/pages/auth/mentor/mentorRegister/mentorRegister.jsx, src/pages/auth/userLogin/login/userLogin.jsx, src/pages/auth/userLogin/login/userLogin.module.css
This PR...
- set up redux store using redux-toolkit
- set up apiSlices for authentication
- connects with the API for authentication
-
Fixes #
=> feat: rtk and rtk query setup + user login setup

package-lock.json
Reverts AltCamp/altcampv1-frontend#79
no file changes
=> Revert "Modals"

src/pages/dashboard/pages/community/community.jsx
This PR...
- reversed the order of the question list so as to show the latest question at the top
-
Fixes #
=> fix: reversed the order of the question list

src/pages/auth/regularStudent/regularStudentRegister/regularStudentRegister.jsx, src/pages/auth/regularStudent/regularStudentRegister/regularStudentRegister.module.css, src/pages/auth/userLogin/login/userLogin.jsx, src/pages/auth/userLogin/login/userLogin.module.css, src/pages/dashboard/components/topbar/topbar.jsx, src/pages/dashboard/pages/account/account.jsx, src/pages/dashboard/pages/community/askquestionpage/askquestionpage.jsx, src/pages/dashboard/pages/community/askquestionpage/askquestionpage.module.css, src/pages/dashboard/pages/community/questioncard/questioncard.module.css, src/pages/dashboard/pages/community/questionpage/createanswer/createanswer.jsx, src/pages/dashboard/pages/community/questionpage/createanswer/createanswer.module.css, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.module.css
This PR...
- matric null error and added error UIs added
-
Fixes #
=> fix: matric null error and added error UIs

src/pages/auth/regularStudent/regularStudentRegister/regularStudentRegister.jsx, src/pages/dashboard/pages/community/askquestionpage/askquestionpage.module.css
This PR...
- added more track options
-
Fixes #
=> feat: added more track options

package-lock.json, package.json, src/pages/auth/regularStudent/regularStudent.module.css, src/pages/dashboard/components/sidebar/sidebar.jsx, src/pages/dashboard/pages/community/community.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.jsx
This PR...
- installed jwt-decode to implement automatic user logout
-
Fixes #
=> feat: implemented logging user out on token exp

src/pages/auth/mentor/mentorRegister/mentorRegister.module.css
This PR...
- Made changes to the name input display for mobile screens
-
Fixes #
=> feat: fixed the name input display for mobile

package-lock.json, src/pages/dashboard/pages/notifications/modals/filterModal.jsx, src/pages/dashboard/pages/notifications/modals/filterModal.module.css, src/pages/dashboard/pages/notifications/modals/sortModal.module.css
This PR...
Worked on the positioning
-
-
Fixes #
=> Worked on the Modal Positioning

src/pages/dashboard/pages/notifications/modals/filterModal.jsx, src/pages/dashboard/pages/notifications/modals/filterModal.module.css, src/pages/dashboard/pages/notifications/modals/sortModal.module.css
Reverts AltCamp/altcampv1-frontend#99
=> Revert "Worked on the Modal Positioning"

src/main.jsx, src/pages/auth/regularStudent/regularStudentRegister/regularStudentRegister.jsx, src/pages/auth/userLogin/login/userLogin.jsx, src/pages/dashboard/components/sidebar/sidebar.jsx, src/pages/dashboard/pages/community/editquestionpage/editquestionpage.jsx, src/pages/dashboard/pages/community/editquestionpage/editquestionpage.module.css, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.module.css, src/pages/dashboard/pages/index.jsx, src/pages/dashboard/pages/users/users.jsx
This PR...
- questions can now be edited and users route added
-
Fixes #
=> feat: questions can now be edited and users route added, answers can be created

src/pages/dashboard/pages/notifications/notifications.jsx, src/pages/dashboard/pages/notifications/notifications.module.css
=> feat: responsiveness for notification.

src/pages/dashboard/pages/community/questionpage/answercard/answercard.jsx, src/pages/dashboard/pages/community/questionpage/answercard/answercard.module.css
This PR...
- mentors answers now carries Instructor badge
-
Fixes #
=> feat: mentors answers now carries Instructor badge

index.html, package-lock.json, package.json, src/app/slices/apiSlices/communitySlices/answerSlice.js, src/main.jsx, src/pages/auth/userLogin/loginGroup.jsx, src/pages/dashboard/pages/community/community.jsx, src/pages/dashboard/pages/community/questioncard/questioncard.jsx, src/pages/dashboard/pages/community/questionpage/answercard/answercard.jsx, src/pages/dashboard/pages/community/questionpage/answercard/answercard.module.css, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.module.css
This PR...
- slug reaced title as dynamic route 
- questions can now be shared on different socials
- installed Sharesocial to handle share feature 
- 
Fixes #
=> feat: slug reaced title as dynamic route & questions can now be shared on different socials

src/app/slices/apiSlices/communitySlices/questionSlice.js, src/pages/dashboard/pages/community/questionpage/answercard/answercard.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.jsx
This PR...
- question upvote and downvote now works in real time
-
Fixes #
=> fixed: question upvote and downvote now works in real time

src/pages/dashboard/pages/users/users.module.css
=> update to user style css

src/main.jsx, src/pages/dashboard/pages/users/userProfile/userProfile.jsx, src/pages/dashboard/pages/users/userProfile/userProfile.module.css, src/pages/dashboard/pages/users/users.jsx, src/pages/dashboard/pages/users/users.module.css
=> update on user

src/main.jsx, src/pages/dashboard/pages/community/questioncard/questioncard.jsx, src/pages/dashboard/pages/community/questionpage/answercard/answercard.module.css, src/pages/dashboard/pages/community/questionpage/questionpage.jsx
=> feat: question page route updated

src/main.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.jsx
=> feat: shared link metadata

src/components/Navbar.jsx, src/components/Navbar.module.css
=> Update hover event to click event in Nav

package-lock.json, src/pages/dashboard/pages/notifications/notifications.module.css
=> feat: updated responsiveness on the notification.

src/components/Navbar.jsx, src/components/Navbar.module.css
Reverts AltCamp/altcampv1-frontend#136
=> Revert "Update hover event to click event in Nav"

package-lock.json, src/pages/dashboard/pages/notifications/notifications.module.css
Reverts AltCamp/altcampv1-frontend#137
=> Revert "feat: updated responsiveness on the notification."

src/components/Navbar.module.css
=> Update hover event to click event on Nav

src/pages/dashboard/pages/notifications/notifications.module.css
=> new updated responsiveness on the notification

src/pages/dashboard/pages/account/account.jsx, src/pages/dashboard/pages/account/changeprofilepicture/picturechange.module.css, src/pages/dashboard/pages/account/myprofile/myprofile.jsx, src/pages/dashboard/pages/users/userProfile/userProfile.jsx, src/pages/dashboard/pages/users/userProfile/userProfile.module.css
This PR...makes changes on display picture in both account and user routes
-
-
Fixes #
=> display update

src/pages/dashboard/pages/bookmarks/bookmarks.module.css
=> feat: responsiveness for bookmark page

src/components/Navbar.jsx, src/components/Navbar.module.css, src/pages/landing/landing.module.css
=> Update landing page breakpoints

src/pages/dashboard/pages/community/questioncard/questioncard.jsx, src/pages/dashboard/pages/community/questioncard/questioncard.module.css, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.module.css, src/pages/dashboard/pages/feed/feed.jsx
=> feat: author image plugged in

src/app/slices/apiSlices/feedSlice.js, src/main.jsx, src/pages/dashboard/pages/community/questioncard/questioncard.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.module.css, src/pages/dashboard/pages/feed/createpost/createpost.jsx, src/pages/dashboard/pages/feed/createpost/createpost.module.css, src/pages/dashboard/pages/feed/feed.jsx, src/pages/dashboard/pages/feed/feed.module.css, src/pages/dashboard/pages/feed/postcard/postcard.jsx, src/pages/dashboard/pages/feed/postcard/postcard.module.css, src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.jsx, src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.module.css, src/pages/dashboard/pages/feed/postpage/postpage.jsx, src/pages/dashboard/pages/feed/postpage/postpage.module.css, src/pages/dashboard/pages/index.jsx
This PR...
- users can now:
- like posts
- create comments
- like comments
- create post on the feed page
-
Fixes #
=> feat: comments, likes, posts

src/app/slices/apiSlices/authSlice.js, src/app/slices/apiSlices/feedSlice.js, src/components/Navbar.jsx, src/pages/auth/auth.module.css, src/pages/auth/register/register.module.css, src/pages/dashboard/components/topbar/topbar.jsx, src/pages/dashboard/pages/feed/createpost/createpost.module.css, src/pages/dashboard/pages/feed/feed.module.css, src/pages/dashboard/pages/feed/postpage/postpage.jsx, src/pages/error/error.jsx, src/pages/error/error.module.css
=> feat: createpost mobile overflow

src/pages/dashboard/components/topbar/topbar.jsx, src/pages/dashboard/pages/feed/feed.jsx, src/pages/dashboard/pages/feed/postcard/postcard.jsx, src/pages/dashboard/pages/feed/postpage/postpage.module.css
=> feat: post list updates after new post creation

src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkCard.jsx, src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkCardStyles.module.css, src/pages/dashboard/pages/bookmarks/bookmarks.jsx, src/pages/dashboard/pages/bookmarks/bookmarks.module.css
=> feat: update to bookmark page

src/main.jsx, src/pages/dashboard/components/bookmarkmodal/bookmarkmodal.jsx, src/pages/dashboard/components/bookmarkmodal/bookmarkmodal.module.css, src/pages/dashboard/pages/community/community.jsx, src/pages/dashboard/pages/community/questioncard/questioncard.jsx, src/pages/dashboard/pages/community/questionpage/answercard/answercard.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/feed/postcard/postcard.jsx, src/pages/dashboard/pages/feed/postcard/postcard.module.css, src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.jsx, src/pages/dashboard/pages/feed/postpage/postpage.jsx, src/pages/dashboard/pages/feed/postpage/postpage.module.css
=> feat: added bookmark modal for all contents

src/pages/dashboard/pages/bookmarks/bookmarks.jsx, src/pages/dashboard/pages/community/community.jsx
=> feat: made pagination display conditional

src/pages/dashboard/components/sidebar/sidebar.module.css, src/pages/dashboard/pages/bookmarks/bookmarks.jsx
=> feat: sorted bookmark list to display in reverse

src/pages/auth/register/register.jsx, src/pages/auth/register/register.module.css, src/pages/auth/userLogin/login/userLogin.module.css, src/pages/dashboard/pages/account/changeprofilepicture/picturechange.jsx, src/pages/dashboard/pages/account/hooks/useMediaHandler.js, src/pages/dashboard/pages/account/myprojects/uploadproject/uploadproject.jsx, src/pages/dashboard/pages/feed/createpost/createpost.jsx
This PR...
- add password pattern guide
- updated useImageHandler to useMediaHandler
-
Fixes #
=> feat: add password pattern guide

src/pages/dashboard/pages/community/questionpage/answercard/answercard.jsx, src/pages/dashboard/pages/feed/postcard/postcard.jsx, src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.jsx, src/pages/dashboard/pages/feed/postpage/postpage.jsx
=> feat: populate bookmark input with contents

src/app/slices/apiSlices/communitySlice.js, src/pages/dashboard/pages/community/community.jsx, src/pages/dashboard/pages/community/community.module.css
=> feat: pagination for community page

src/app/slices/apiSlices/feedSlice.js, src/pages/dashboard/pages/community/community.jsx, src/pages/dashboard/pages/feed/feed.jsx, src/pages/dashboard/pages/feed/feed.module.css
=> feat:  see more for post page

src/pages/dashboard/components/bookmarkmodal/bookmarkmodal.jsx, src/pages/dashboard/pages/feed/createpost/createpost.jsx
=> feat: add autofocus 2 bookmark & createPost modals

src/pages/dashboard/pages/feed/feed.jsx
=> bug: display posts on page load + pagination

src/pages/dashboard/pages/bookmarks/bookmarks.jsx, src/pages/dashboard/pages/bookmarks/bookmarks.module.css, src/pages/dashboard/pages/community/community.module.css
This PR...
-
-
- [#] added/updated a component
Fixes #
=> change to bookmarks

src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkCard.jsx, src/pages/dashboard/pages/community/community.jsx, src/pages/dashboard/pages/community/questionpage/answercard/answercard.jsx, src/pages/dashboard/pages/community/questionpage/answercard/answercard.module.css, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.module.css, src/pages/dashboard/pages/feed/createpost/createpost.jsx, src/pages/dashboard/pages/feed/feed.jsx, src/pages/dashboard/pages/feed/postcard/postcard.jsx, src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.jsx, src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.module.css, src/pages/dashboard/pages/feed/postpage/postpage.jsx, src/pages/dashboard/pages/feed/postpage/postpage.module.css
=> feat: scroll-in-to-view, enterKey and misc.

src/pages/dashboard/pages/account/profileEdit/editprofile.jsx, src/pages/dashboard/pages/users/users.jsx, src/pages/dashboard/pages/users/users.module.css
=> update on edit profile

src/app/slices/apiSlices/bookmarkSlice.js, src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkCard.jsx, src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkcard.module.css, src/pages/dashboard/pages/bookmarks/bookmarks.jsx, src/pages/dashboard/pages/bookmarks/bookmarks.module.css
=> feat: pagination for bookmark

src/pages/auth/register/register.jsx
=> bug: remove programmatic navigation to dashboard

src/components/Toaster/Toaster.module.css, src/pages/auth/register/register.jsx, src/pages/auth/userLogin/login/userLogin.jsx, src/pages/dashboard/components/sidebar/sidebar.jsx, src/pages/dashboard/pages/community/askquestionpage/askquestionpage.jsx, src/pages/dashboard/pages/community/questioncard/questioncard.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/feed/postcard/postcard.jsx
=> bug: short circuit error mopups

src/pages/dashboard/pages/bookmarks/bookmarks.module.css
This PR...
-
-
- [#] added/updated a component
Fixes #
=> Bookmark changes

src/pages/dashboard/pages/users/userProfile/userProfile.module.css
=> update on userProfile

.gitignore, CONTRIBUTING.md, example.env, package-lock.json, package.json, src/app/url.js, src/pages/dashboard/pages/community/richeditor/richeditor.jsx, src/pages/dashboard/pages/notifications/notifications.jsx
=> docs: env, contribution guide, & unused pkg -rm

src/pages/dashboard/pages/users/userProfile/userProfile.module.css, src/pages/dashboard/pages/users/users.module.css
=> update on user and userProfile styling

src/app/slices/apiSlices/accountSlices/accountMutationSlice.js, src/app/url.js, src/pages/dashboard/pages/feed/postcard/postcard.jsx, src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.jsx, src/pages/dashboard/pages/feed/postpage/postpage.jsx
=> bug: fix negative vote count for posts & comments

src/pages/dashboard/pages/bookmarks/bookmarks.jsx
=> refactor: remove redundant sorting logic

.github/workflows/altcamplive.js.yml
=> ci: test deployment workflow

src/pages/landing/landing.jsx
=> bug: anchor tag leading to 404 on main site

.github/workflows/altcamplive.js.yml
=> chore: rewrite github action workflow

.github/workflows/altcamplive.js.yml, src/components/Toaster/Toaster.jsx, src/pages/auth/register/register.jsx, src/pages/auth/register/verifyemail/verifyemail.jsx, src/pages/auth/userLogin/login/userLogin.jsx, src/pages/dashboard/pages/account/changeprofilepicture/picturechange.jsx, src/pages/dashboard/pages/account/hooks/useMediaHandler.js, src/pages/dashboard/pages/community/askquestionpage/askquestionpage.jsx, src/pages/landing/landing.jsx
=> sync: sync with dev

package-lock.json, package.json, postcss.config.js, src/index.css, src/pages/auth/userLogin/login/userLogin.jsx, src/pages/dashboard/components/sidebar/sidebar.module.css, src/pages/dashboard/pages/account/account.module.css, src/pages/dashboard/pages/bookmarks/bookmarks.module.css, src/pages/dashboard/pages/community/community.module.css, src/pages/dashboard/pages/community/questioncard/questioncard.module.css, src/pages/dashboard/pages/community/questionpage/answercard/answercard.module.css, src/pages/dashboard/pages/community/questionpage/questionpage.module.css, src/pages/dashboard/pages/feed/postcard/postcard.module.css, src/pages/dashboard/pages/feed/postpage/postcomment/postcomment.module.css, src/pages/dashboard/pages/feed/postpage/postpage.module.css, src/pages/dashboard/pages/notifications/notifications.module.css, src/pages/dashboard/pages/users/users.module.css, tailwind.config.js
=> build/style: install & setup tailwindcss & change end/start to flex-end/flex-start

package-lock.json, package.json, src/pages/dashboard/pages/account/changeprofilepicture/picturechange.jsx, src/pages/dashboard/pages/account/profileEdit/editprofile.jsx, src/pages/dashboard/pages/bookmarks/bookmarks.jsx
=> feat: add toaster to editProfile

tailwind.config.js
=> ci: extend tailwind's colors in tailwindconfig instead of overwriting

package.json, src/index.css, src/pages/auth/userLogin/login/userLogin.jsx, tailwind.config.js
=> feat: convert login page css/styles to tailwindcss

CONTRIBUTING.md, README.md
This PR...
- Changed StudyBuddy to AltCamp in CONTRIBUTION.md
- Updated list of tools used in README.md
-
Fixes #
=> chore: update README.md with key tools used in this project

README.md
This PR...
-
- Adds links to API documentation, Postman collection, Figma, and Product management document.
Fixes #
=> docs: add api, figma, and coda docs links to README.md

src/app/constants/api.js, src/app/slices/apiSlices/accountSlice.js, src/app/slices/apiSlices/authSlice.js, src/app/slices/apiSlices/bookmarkSlice.js, src/app/slices/apiSlices/communitySlice.js, src/app/slices/apiSlices/feedSlice.js, src/app/slices/apiSlices/forgotPasswordSlice.js, src/app/url.js
This PR...
- Creates a single source of truth for API endpoints/URLs thereby making the code DRY
-
Fixes #
=> refactor: populate url.js with urls & use in all API slices

src/pages/dashboard/pages/bookmarks/bookmarks.jsx
=> feat: add illustration/ui for empty bookmarks section

src/pages/dashboard/pages/bookmarks/bookmarkCard/bookmarkCard.jsx
This PR...
- Closes #248 
-
Fixes #
=> fix: properly render bookmark cards when bookmarked resources has been deleted

package-lock.json, package.json, src/index.css, src/pages/landing/landing.jsx, src/pages/landing/landing.module.css, yarn.lock
=> feat: Add carousels to landing page and update content

src/pages/dashboard/pages/community/questionpage/answercard.jsx
=> style: whitespace.

.github/workflows/altcamplive.js.yml, src/pages/dashboard/components/topbar.jsx, src/pages/dashboard/layout/layout.jsx, src/pages/dashboard/pages/account/hooks/useMediaHandler.js, src/pages/dashboard/pages/bookmarks/bookmarks.jsx, src/pages/dashboard/pages/community/community.jsx, src/pages/dashboard/pages/community/questioncard.jsx, src/pages/dashboard/pages/community/questionpage/answercard.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/feed/createpost.jsx, src/pages/dashboard/pages/feed/feed.jsx, src/pages/dashboard/pages/feed/postcard.jsx, src/pages/dashboard/pages/feed/postpage/postcomment.jsx, src/pages/dashboard/pages/feed/postpage/postpage.jsx
This PR...
- ci: add an environment variable for base URL
-  layout outlets overflow-scroll hidden contents on mobile devices
Fixes #
=> fix: layout outlets overflow-scroll hidden contents on mobile devices

.github/workflows/altcamplive.js.yml, src/pages/dashboard/components/topbar.jsx, src/pages/dashboard/layout/layout.jsx, src/pages/dashboard/pages/account/hooks/useMediaHandler.js, src/pages/dashboard/pages/bookmarks/bookmarks.jsx, src/pages/dashboard/pages/community/community.jsx, src/pages/dashboard/pages/community/questioncard.jsx, src/pages/dashboard/pages/community/questionpage/answercard.jsx, src/pages/dashboard/pages/community/questionpage/questionpage.jsx, src/pages/dashboard/pages/feed/createpost.jsx, src/pages/dashboard/pages/feed/feed.jsx, src/pages/dashboard/pages/feed/postcard.jsx, src/pages/dashboard/pages/feed/postpage/postcomment.jsx, src/pages/dashboard/pages/feed/postpage/postpage.jsx
=> fix: set appropriate padding for feed and community outlets

.github/workflows/altcamplive.js.yml
Reverts AltCamp/altcampv1-frontend#274
=> Revert "Main"
